[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set t_Co=256
  set laststatus=2
  let g:lightline = {
    \'colorscheme': 'tender',
    \'active': {
    \  'left': [
    \    ['mode', 'paste'],
    \    ['gitbranch', 'readonly', 'filename', 'modified'],
    \  ],
    \  'right': [
    \    ['fileformat', 'fileencoding', 'filetype']
    \  ]
    \},
    \'component_function': {
    \  'gitbranch': 'fugitive#head',
    \},
  \}
'''


[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = 'yaml'


[[plugins]]
repo = 'tpope/vim-fugitive'


[[plugins]]
repo = 'airblade/vim-gitgutter'


[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_auto_colors = 1
  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=darkgray
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=gray
'''


[[plugins]]
repo = 'Shougo/context_filetype.vim'


[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']


[[plugins]]
repo = 'junegunn/fzf'
build = './install --xdg --all'
merged = 0


[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'


[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_set_loclist = 0
  let g:ale_set_quickfix = 1
  let g:ale_open_list = 1

  let g:ale_sh_shellcheck_executable = 'shellcheck'
  let g:ale_completion_enabled = 1

  let g:ale_lint_on_enter = 1
  let g:ale_lint_on_insert_leave = 1
  let b:ale_linters = {
        \'sh': ['shellcheck'],
        \'tf': ['tflint']
        \}

  let g:ale_fix_on_save = 1
  let b:ale_fixers = {
        \'tf': ['terraform']
  \}
'''
