#[[plugins]]
#repo = 'NLKNguyen/cloudformation-syntax.vim'
#hook_add = '''
#  let g:AWSVimValidate = 1
#  augroup aws
#    autocmd!
#    autocmd BufNewFile,BufRead *.cfn.json set syntax=cloudformation
#    autocmd BufNewFile,BufRead *.cfn.yaml set syntax=cloudformation
#  augroup END
#'''

#[[plugins]]
#repo = 'lunarxlark/aws-cfn-snippet.vim'
#depends = ['Shougo/neosnippet']
