[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set t_Co=256
  set laststatus=2
  let g:lightline = {
    \'colorscheme': 'tender',
    \'active': {
    \  'left': [
    \    ['mode', 'paste'],
    \    ['gitbranch', 'readonly', 'filename', 'modified'],
    \    ['linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok']
    \  ],
    \  'right': [
    \    ['fileformat', 'fileencoding', 'filetype']
    \  ]
    \},
    \'component_function': {
    \  'gitbranch': 'fugitive#head',
    \},
  \}
'''

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']
hook_add = '''
  let g:lightline#ale#indicator_warnings = '⚠'
  let g:lightline#ale#indicator_errors = '⨉'
  let g:lightline#ale#indicator_ok = '⬥ ok'

  let g:lightline.component_expand = {
        \ 'linter_checking': 'lightline#ale#checking',
        \ 'linter_warnings': 'lightline#ale#warnings',
        \ 'linter_errors': 'lightline#ale#errors',
        \ 'linter_ok': 'lightline#ale#ok',
        \ }

  let g:lightline.component_type = {
        \ 'linter_checking': 'left',
        \ 'linter_warnings': 'warning',
        \ 'linter_errors': 'error',
        \ 'linter_ok': 'left',
        \ }
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = 'yaml'


[[plugins]]
repo = 'tpope/vim-fugitive'


[[plugins]]
repo = 'airblade/vim-gitgutter'


[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_auto_colors = 1
  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=darkgray
  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=gray
'''


[[plugins]]
repo = 'Shougo/context_filetype.vim'


[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']


[[plugins]]
repo = 'junegunn/fzf'
build = './install --xdg --all'
merged = 0


[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'


[[plugins]]
repo = 'w0rp/ale'
on_ft = 'sh,tf,go'
hook_add = '''
  let g:ale_set_loclist = 0
  let g:ale_set_quickfix = 1
  let g:ale_open_list = 1

  let g:ale_sh_shellcheck_executable = 'shellcheck'
  let g:ale_completion_enabled = 1

  let g:ale_lint_on_enter = 1
  let g:ale_lint_on_insert_leave = 1
  let b:ale_linters = {
        \'sh': ['shellcheck'],
        \'tf': ['tflint']
        \}

  let g:ale_fix_on_save = 1
  let b:ale_fixers = {
        \'tf': ['terraform']
  \}
'''

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'
hook_add = '''
  let g:terraform_aligh = 1
  let g:terraform_fold_sections = 1
  let g:terraform_remap_spacebar = 1
  let g:terraform_fmt_on_save = 1
'''
