[[plugins]]
repo = 'hashivim/vim-vagrant'

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'
hook_add = '''
  " Allow vim-terraform to override your ```.vimrc``` indentation syntax for matching files.
  " Defaults to 0 which is off.
  let g:terraform_align=1
  " ALlow vim-terraform to automatically fold (hide until unfolded) sections of terraform code.
  " Defaults to 0 which is off.
  let g:terraform_fold_sections=1
  " Allow vim-terraform to re-map the spacebar to fold/unfold.
  " This works in conjunction with ```let g:terraform_fold_sections=1``` which should be enabled if you plan to use this feature.
  " Defaults to 0 which is off.
  let g:terraform_remap_spacebar=0
  " Run terraform fmt automatically when saving *.tf or *.tfvars files.
  let g:terraform_fmt_on_save=1
'''

[[plugins]]
repo = 'juliosueiras/vim-terraform-completion'
on_ft = 'terraform'
depends_on = ['deoplete.nvim', 'vim-terraform']
hook_add = '''
  " (Optional)Remove Info(Preview) window
  "set completeopt-=preview
  " (Optional)Hide Info(Preview) window after completions
  autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
  autocmd InsertLeave * if pumvisible() == 0|pclose|endif
  " (Optional) Enable terraform plan to be include in filter
  let g:syntastic_terraform_tffilter_plan = 0
  " (Optional) Default: 0, enable(1)/disable(0) plugin's keymapping
  let g:terraform_completion_keys = 1
  " (Optional) Default: 1, enable(1)/disable(0) terraform module registry completion
  let g:terraform_registry_module_completion = 1

  let g:neosnippet#snippets_directory='~/.cache/dein/repos/github.com/juliosueiras/vim-terraform-completion/snippets/'
'''

[[plugins]]
repo = 'hashivim/vim-packer'
