[metadata]
name = "futurepunk"
author = "lunarxlark"
origin_url = "https://github.com/lunarxlark/futurepunk.nvim"

[colors]
foreground = "#fdf3ce"
background = "#040F1C"
cursor_bg = "#fdf3ce"
cursor_border = "#fdf3ce"
cursor_fg = "#08041C"
compose_cursor = "#F98C5D"
selection_bg = "#151C36"
selection_fg = "#fdf3ce"
scrollbar_thumb = "#31486f"
split = "#8391a9"
visual_bell = "#FBAE8D"
ansi = ["#040F1C", "#F95D5D", "#50c5cd", "#F9C05D", "#0673A2", "#AF4141", "#057272", "#faeece"]
brights = ["#151C36", "#FB8D8D", "#055172", "#F9C05D", "#3F98BF", "#FB8D8D", "#3FBFBF", "#e9e9e9"]

[colors.indexed]
16 = "#F95D5D"
17 = "#F98C5D"

[colors.tab_bar]
background = "#08041C"
inactive_tab_edge = "#31486f"
inactive_tab_edge_hover = "#22324e"

[colors.tab_bar.active_tab]
bg_color = "#faeece"
fg_color = "#08041C"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#31486f"
fg_color = "#faeece"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#31486f"
fg_color = "#ebdbb2"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#040F1C"
fg_color = "#d5c4a1"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#040F1C"
fg_color = "#ebdbb2"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

